import dynamic from "next/dynamic";
const Header = dynamic(() => import("@/components/header"));
import SmokeEffect from "@/components/smokeEffect/SmokeEffect";
import "./globals.css";
import "swiper/css";
import Footer from "@/components/footer";
import ChooseWhere from "@/rendering/homePage/chooseWhere";
import NewsLatter from "@/rendering/homePage/newsLatter";
import Faq from "@/rendering/homePage/faq";
import { Toaster } from "sonner";
import MobileHeader from "../components/mobileHeader";

export const metadata = {
	title: "Secure fx",
	description: "Generated by create next app",
	icons: {
		icon: "/assets/logo/secure-fx-logo.svg",
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				<>
					<MobileHeader />
					{children}
					<ChooseWhere />
					{/* <NewsLatter /> */}
					<Faq />
					<Footer />
					<Toaster
						position="top-right"
						theme="dark"
						toastOptions={{
							style: {
								background: "#131315",
							},
						}}
					/>
					<SmokeEffect />
				</>
			</body>
		</html>
	);
}
